
image: gcc

build:
  stage: build
  tags:
    - build_server
  script:
    - cd Engine/ScriptCore
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . > BuildLog.txt
  artifacts:
    paths:
      - Engine/ScriptCore/build/*.a
      - Engine/ScriptCore/build/tests/*
      - Engine/ScriptCore/build/BuildLog.txt


test:
  stage: test
  tags:
    - build_server
  script:
    - cd build
    - make test
